

export type User {
  id: String!
  createdAt: String!
  updatedAt: String?
  userPhoto: String?
  name: String!
  userName: String!
  friends: String?
  subscription: String?
  status: String?
  email: String!
  password: String!
  token: String!
  isPostView: String!
  isProfileView: String!
}


